apiVersion: v1
kind: Pod
metadata:
  name: gateway
  labels:
   app: gateway
spec:
  containers:
  - image: mikewasson/appgw:latest
    name: gateway
    ports:
      - containerPort: 80
      - containerPort: 443
---
apiVersion: v1
kind: Pod
metadata:
  name: app1
  labels:
   app: app1
spec:
  containers:
  - image: mikewasson/app1
    name: app1
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: app1
spec:
  selector:
    app: app1
  ports:
    - port: 80
